### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by WGzeyu** [BeatTogether/BeatTogether.MasterServer#11]
Hi, I would like to run BeatTogether server to solve the problem of difficult connection in China, is there any documentation available?
I tried to run it directly with docker, but I encountered an error, are there some steps missing?

<details>
  <summary>logs (click to expand)</summary>
  <pre>

```
PS C:\Users\WGzeyu> docker run ghcr.io/pythonology/beat-together-master-server:sha-5c455cd
Unhandled exception. RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> System.AggregateException: One or more errors occurred. (Connection failed)
 ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)
   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)
   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection()
   at Autobus.Transports.RabbitMQ.RabbitMQTransportBuilder.Build()
   at Autobus.AutobusBuilder.UseTransport[TTransportBuilder](Action`1 onBuild)
   at Autobus.AutobusBuilderExtensions.UseRabbitMQTransport(IAutobusBuilder builder, Action`1 onBuild)
   at BeatTogether.Extensions.AutobusBuilderExtensions.UseRabbitMQTransport(IAutobusBuilder autobusBuilder, IConfiguration configuration)
   at BeatTogether.Extensions.HostBuilderExtensions.<>c.<UseAutobus>b__0_0(HostBuilderContext hostBuilderContext, IAutobusBuilder builder)
   at Autobus.HostBuilderExtensions.<>c__DisplayClass1_1.<UseAutobus>b__1(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BeatTogether.MasterServer.Program.Main(String[] args) in /app/BeatTogether.MasterServer/Program.cs:line 9
```

</pre>
</details>

**Comment by Kevman95** [comment]
We don't have documentation currently. That is in progress of being written.

You need to run a RabbitMQ service. That is what is needed to route messages. Once ran you should be set.

**Comment by WGzeyu** [comment]
I have run the RabbitMQ service, but I still get this error.

**Comment by Kevman95** [comment]
Please reach out to me on Discord for assistance.

**Comment by WGzeyu** [comment]
Thanks to **Kevman95** patience and help, all the problems are solved!

Now I use the following configuration.
First, block access to ports 5672 and 15672 from the Internet via iptables, allowing 127.0.0.1.
Run docker directly from a linux-based system with the following command.
```
docker run -d --log-opt max-size=4m -it --rm --name rabbitmq --net=host rabbitmq:3.9-management
docker run -d --log-opt max-size=4m --restart=on-failure -v /root/master-server.json:/app/appsettings.json --net=host ghcr.io/pythonology/beat-together-master-server:master
docker run -d --log-opt max-size=4m --restart=on-failure -v /root/dedicated-server.json:/app/appsettings.json --net=host ghcr.io/pythonology/beat-together-dedicated-server:master
docker run -d --log-opt max-size=4m --restart=on-failure -v /root/status-api.json:/app/appsettings.json -p 23280:80 ghcr.io/pythonology/beat-together-status-api:master
```
`/root/master-server.json`：
```
{
  "MasterServer": {
    "EndPoint": "[Network card IP]:2328"
  },
  "Messaging": {
    "RabbitMQ": {
      "EndPoint": "amqp://127.0.0.1:5672"
    }
  },
  "Serilog": {
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Warning"
      }
    },
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Async" ],
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "File",
              "Args": {
                "path": "logs/BeatTogether.MasterServer-{Date}.log",
                "rollingInterval": "Day"
              }
            }
          ]
        }
      }
    ]
  }
}
```
   
`/root/dedicated-server.json`：
```
{
  "Server": {
    "HostName": "[Public IP]",
    "BasePort": 30000,
    "RelayServers": {
      "MaximumSlots": 10000
    }
  },
  "Serilog": {
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Warning"
      }
    },
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Async" ],
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "File",
              "Args": {
                "path": "logs/BeatTogether.DedicatedServer-{Date}.log",
                "rollingInterval": "Day"
              }
            }
          ]
        }
      }
    ]
  }
}
```
   
`/root/status-api.json`：
```
{
  "Status": {
    "MinimumAppVersion": "1.17.1"
  },
  "Quickplay": {
    "PredefinedPacks": [
      {
        "order": 0,
        "packId": "ALL_LEVEL_PACKS"
      },
      {
        "order": 1,
        "packId": "BUILT_IN_LEVEL_PACKS"
      }
    ],
    "LocalizedCustomPacks": [
      {
        "serializedName": "customlevels",
        "order": 2,
        "localizedNames": [
          {
            "language": "English",
            "packName": "Custom"
          }
        ],
        "packIds": [
          "custom_levelpack_CustomLevels"
        ]
      }
    ]
  },
  "Serilog": {
    "File": {
      "Path": "logs/BeatTogether.Status.Api-{Date}.log"
    }
  }
}
```

**Comment by Hoxtop** [comment]
An update on the instructions above: 
1. the "Server" field in `dedicated-server.json` has been renamed to "Node". 
2. ~~The ghcr.io/pythonology/beat-together-* images also haven't been updated in 3 months (at the time of writing), so you need to build them yourself.~~ Change the ghcr.io/pythonology/beat-together-* image URLs to ghcr.io/beattogether/beat-together-* (i.e. \*/pythonology/\* -> \*/beattogether/\*)
3. "MinimumAppVersion" is "1.21.0" on the server right now. Not sure what the effect of a wrong version number is

**Comment by WGzeyu** [comment]
> An update on the instructions above:
> 
> 1. the "Server" field in `dedicated-server.json` has been renamed to "Node".
> 2. The ghcr.io/pythonology/beat-together-* images also haven't been updated in 3 months (at the time of writing), so you need to build them yourself.
> 3. "MinimumAppVersion" is "1.21.0" on the server right now. Not sure what the effect of a wrong version number is

https://gist.github.com/qe201020335/31617e49041cda79896f3ebbcc8ffac6

**Comment by Kevman95** [comment]
@Hoxtop you don't have to build it yourself. The only change is the URL. Remove pythonology and replace it with beattogether.

**Comment by qe201020335** [comment]
The config files above are overriding the default values for all things. However, base on my understanding of asp.net and the code, most of those were already built in so there is no need to actually override all of them.

A better way is to create `appsettings.Production.json` file which the server will load on start up instead of overriding `appsettings.json`. Then in the production json file, only override what is necessary, for example which ip and port to listen on.

This is also what I did in the gist mentioned [above](https://github.com/BeatTogether/BeatTogether.MasterServer/issues/11#issuecomment-1151406068) by @WGzeyu
